baseURL = 'https://jacksoncampolattaro.github.io/'
languageCode = 'en-us'
title = 'Jackson Campolattaro'
theme = 'custom'

[params]
    scheme = "light" # light, dark, gray or preference
    description = "Computer Engineering student at TU Delft with an enthusiasm for Open Source software"
    firstname = "Jackson"
    lastname = "Campolattaro"
    email = "jackson.campolattaro@gmail.com"
    github = "JacksonCampolattaro"
    linkedin = "jacksoncampolattaro"

[menu]
    [[menu.main]]
        name = "Contact"
        url = "/contact"
    [[menu.main]]
        name = "About"
        url = "/about"
#    [[menu.contacts]]
#        name = "Github"
#        url = "https://github.com/JacksonCampolattaro"
#    [[menu.contacts]]
#        name = "LinkedIn"
#        url = "https://www.linkedin.com/in/jacksoncampolattaro/"
#    [[menu.contacts]]
#        name = "Email"
#        url = "mailto:j.campolattaro@student.tudelft.nl"
